update  README.md
apache/linkis pull request #4259
Opened 2023-02-23 08:30 UTC by binbinCheng

**Update the content in the README document**

2023-02-26 06:20 UTC, casionone approved these changes
LGTM

2023-02-26 06:22 UTC, casionone commented on README_CN.md
> +| **引擎名** | **支持底层组件版本<br/>(默认依赖版本)** | **Linkis 1.X 版本要求** | **是否默认包含在发布包中** | **说明** |
About **Linkis 版本要求** 
It is recommended to use version 1.0.3 not 1.0.0_rc1

2023-02-26 08:32 UTC, casionone requested changes
About **Linkis 版本要求** 
It is recommended to use version 1.0.3 not 1.0.0_rc1

2023-02-28 07:17 UTC, binbinCheng commented on README_CN.md
> +| **引擎名** | **支持底层组件版本<br/>(默认依赖版本)** | **Linkis 1.X 版本要求** | **是否默认包含在发布包中** | **说明** |
already edited

2023-03-01 08:09 UTC, peacewong approved these changes
LGTM.

2023-03-02 07:19 UTC, casionone approved these changes

2023-03-02 07:20 UTC, merged